name: Build kernel and create .deb files

on:
  workflow_dispatch:

jobs:

  build:
   strategy:
        matrix:
          version: ['6.6.y']
          kernel-version: ['6.6.31']

   runs-on: ubuntu-latest

   steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Install necessary  package
          run: |
                sudo apt-get update && sudo apt-get install -y build-essential fakeroot bc python3 bison flex libelf-dev libssl-dev libncurses-dev dwarves lz4 devscripts dkms vim make wget

        - name: Get kernel source
          run: |
                # wget https://mirrors.edge.kernel.org/pub/linux/kernel/${{matrix.version}}/linux-${{matrix.kernel-version}}.tar.xz
                wget https://github.com/unifreq/linux-6.6.y/archive/refs/tags/linux-6.6.31.tar.gz

        - name: Extract kernel source
          run: |
                tar -xzvf linux-${{matrix.kernel-version}}.tar.gz

        - name: Make configuration ARCH
          working-directory: ${{ github.workspace }}
          run: |
                cd linux-${{matrix.version}}-linux-${{matrix.kernel-version}}/ 
                ls -l
                make ARCH=arm64 defconfig

        - name: Change var configuration
          working-directory: linux-${{matrix.kernel-version}}
          run: |
                sed -i 's/CONFIG_SYSTEM_TRUSTED_KEYS = ""/CONFIG_SYSTEM_TRUSTED_KEYS=""/' .config

        - name: Make kernel and create .deb files
          working-directory: linux-${{matrix.kernel-version}}
          run: |
                nice make -j$(nproc) bindeb-pkg
                cd ..
                ls -l
                mkdir deb_archive
                mv  *.deb deb_archive/
                tar -czvf kernel_deb_files.tar.gz deb_archive/

        - name: Archive .deb files
          uses: actions/upload-artifact@v2
          with:
                name: kernel-deb-files
                path: kernel_deb_files.tar.gz

     
