name: Helm chart release and update index

on:
  push:
    branches:
      -  test

jobs:

 build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
       fetch-depth: 0


    - name: Install necessary  package
      run : |
        sudo apt-get update && sudo apt-get install -y build-essential fakeroot bc python3 bison flex libelf-dev libssl-dev libncurses-dev dwarves lz4 devscripts dkms vim make wget
 
    
    - name : Get kernel source
      run: |
          wget https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.15.105.tar.xz

    - name: Extract kernel source
      run: |
            tar -xf linux-5.15.105.tar.xz
            cd linux-5.15.105/ 

    - name: Make configuration ARCH
      run: |
         make ARCH=i386 defconfig 
    

    - name: Change var configuration 
      run: |
        sed -i 's/CONFIG_SYSTEM_TRUSTED_KEYS = ""/CONFIG_SYSTEM_TRUSTED_KEYS=""/' .config

    - name: Make kernel
      run: |
        nice make -j$(nproc) bindeb-pkg
